"""empty message

Revision ID: bc1fcb5f53bc
Revises: 
Create Date: 2018-10-13 06:25:26.199535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1fcb5f53bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=True),
    sa.Column('optimal', sa.String(length=32), nullable=True),
    sa.Column('freezer', sa.Integer(), nullable=True),
    sa.Column('fridge', sa.Integer(), nullable=True),
    sa.Column('roomtemp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_item'), 'reference', ['item'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('fridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_expiration'), 'fridge', ['expiration'], unique=False)
    op.create_index(op.f('ix_fridge_timestamp'), 'fridge', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridge_timestamp'), table_name='fridge')
    op.drop_index(op.f('ix_fridge_expiration'), table_name='fridge')
    op.drop_table('fridge')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reference_item'), table_name='reference')
    op.drop_table('reference')
    # ### end Alembic commands ###
